### ISSUE TITLE
Recipe App Kahban Board 

### ISSUE THREAD

**Issue by ndorrh** [iAmWaris97/recipe-app#15]
- In this Issue, you will find the link to our kanban board which will give you and idea of How the work was shared between the group members

- [Github Project link](https://github.com/iAmWaris97/recipe-app/projects/1)
- The Team is made of 3 micronaults; @iAmWaris97, @ndorrh, and @erickhansx

**Comment by m05e5** [comment]
**Hi @ndorrh  @iAmWaris97 and @erickhansx 

You did great. Your kanban board is complete!  There is nothing else to say other than... its time to start coding :shipit: 
Congratulations! 🎉 
![CleverScornfulBuffalo-size_restricted](https://user-images.githubusercontent.com/37901469/208869296-5ca9f6cc-a1b5-48fd-bd59-78fd83b35471.gif)

## Highlights
✔️ Clean kanban board

## Optional suggestions



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**m05e5**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._**
